### PR TITLE
Update 404.html

### PR DESCRIPTION
**Pull request by JaydeepRokade**

### CODE REVIEW

**Comment by jepperaskdk** [comment]
@JaydeepRokade Why this change?

**Comment by JaydeepRokade** [comment]
Because it matches above header tag

**Comment by jepperaskdk** [comment]
@JaydeepRokade I don't understand. It looks like a random change serving no purpose.
If you make a pull-request to an open-source project, please describe in details why you are making such change.
I can see you made a similarly random pull-request to the eslint repository here: https://github.com/eslint/eslint/pull/18776

**Comment by JaydeepRokade** [comment]
I told you why I have made change still you are asking the above header
isn't matching in the project

**Comment by jepperaskdk** [comment]
@JaydeepRokade You need to describe it in more detail. 

The error 500 page uses h1 and h3 as well - what do you mean it isn't "matching the project". Please provide some evidence.

**Comment by JaydeepRokade** [comment]
Ok, I will do that.

**Pull request closed without merging**
