### PR TITLE
Added missing div closing tag

### PR DESCRIPTION
**Pull request by filipkrstic**
W3 validator reported open element. This change fixed it.

### CODE REVIEW

**Review by krzysiekpiasecki — COMMENTED** [review]
After formatting the source code it looks like a ```<div id='mainContent'>``` is not properly closed.

**Comment by filipkrstic** [comment]
I thought same, but formatting fails because something is open inside `<div id='mainContent'>`, so i decided to go manually and I found problem on line [1063](https://github.com/filipkrstic/Adminator-admin-dashboard/blob/2cfd6f773e6cbb3bcc04a3b2c9c712b8b3535542/src/index.html#L1063), `<div class="peers fxw-nw ai-c pY-3 pX-10 bgc-white bdrs-2 lh-3/2">` is not closed, and it should be closed on line [1070](https://github.com/filipkrstic/Adminator-admin-dashboard/blob/2cfd6f773e6cbb3bcc04a3b2c9c712b8b3535542/src/index.html#L1070).

**Comment by krzysiekpiasecki** [comment]
You're right the problem is in the chat fragment of HTML. When cutting this fragment from the ```index.html``` source is valid, on the other side cutted fragment is invalid. 

From formatting it looks like the ```<div class="bd bgc-white">``` was not closed. Or am I wrong?

```html
<!-- #Chat ==================== -->
<div class="bd bgc-white">
    <div class="layers">
        <div class="layer w-100 p-20">
            <h6 class="lh-1">Quick Chat</h6>
        </div>
        <div class="layer w-100">
            <!-- Chat Box -->
            <div class="bgc-grey-200 p-20 gapY-15">
                <!-- Chat Conversation -->
                <div class="peers fxw-nw">
                    <div class="peer mR-20">
                        <img class="w-2r bdrs-50p" src="https://randomuser.me/api/portraits/men/11.jpg" alt="">
                    </div>
                    <div class="peer peer-greed">
                        <div class="layers ai-fs gapY-5">
                            <div class="layer">
                                <div class="peers fxw-nw ai-c pY-3 pX-10 bgc-white bdrs-2 lh-3/2">
                                    <div class="peer mR-10">
                                        <small>10:00 AM</small>
                                    </div>
                                    <div class="peer-greed">
                                        <span>Lorem Ipsum is simply dummy text of</span>
                                    </div>
                                </div>
                            </div>
                            <div class="layer">
                                <div class="peers fxw-nw ai-c pY-3 pX-10 bgc-white bdrs-2 lh-3/2">
                                    <div class="peer mR-10">
                                        <small>10:00 AM</small>
                                    </div>
                                    <div class="peer-greed">
                                        <span>the printing and typesetting industry.</span>
                                    </div>
                                </div>
                            </div>
                            <div class="layer">
                                <div class="peers fxw-nw ai-c pY-3 pX-10 bgc-white bdrs-2 lh-3/2">
                                    <div class="peer mR-10">
                                        <small>10:00 AM</small>
                                    </div>
                                    <div class="peer-greed">
                                        <span>Lorem Ipsum has been the industry's</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Chat Conversation -->
                <div class="peers fxw-nw ai-fe">
                    <div class="peer ord-1 mL-20">
                        <img class="w-2r bdrs-50p" src="https://randomuser.me/api/portraits/men/12.jpg" alt="">
                    </div>
                    <div class="peer peer-greed ord-0">
                        <div class="layers ai-fe gapY-10">
                            <div class="layer">
                                <div class="peers fxw-nw ai-c pY-3 pX-10 bgc-white bdrs-2 lh-3/2">
                                    <div class="peer mL-10 ord-1">
                                        <small>10:00 AM</small>
                                    </div>
                                    <div class="peer-greed ord-0">
                                        <span>Heloo</span>
                                    </div>
                                </div>
                            </div>
                            <div class="layer">
                                <div class="peers fxw-nw ai-c pY-3 pX-10 bgc-white bdrs-2 lh-3/2">
                                    <div class="peer mL-10 ord-1">
                                        <small>10:00 AM</small>
                                    </div>
                                    <div class="peer-greed ord-0">
                                        <span>??</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Chat Send -->
            <div class="p-20 bdT bgc-white">
                <div class="pos-r">
                    <input type="text" class="form-control bdrs-10em m-0" placeholder="Say something...">
                    <button type="button" class="btn btn-primary bdrs-50p w-2r p-0 h-2r pos-a r-1 t-1">
                        <i class="fa fa-paper-plane-o"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
```

**Comment by filipkrstic** [comment]
I just checked again. You are right. My mistake, all items in chat fragment from line 1070 are not indented 
properly.
screenshot_2

**Review by krzysiekpiasecki — CHANGES_REQUESTED** [review]
Close the correct markup

**Comment by filipkrstic** [comment]
Done! First commit made this:
screenshot_3

In second commit, proper div tag is closed:
screenshot_4

**Comment by krzysiekpiasecki** [comment]
It's a proof of work. Checked again with the validator?

**Review by krzysiekpiasecki — APPROVED** [review]

**Comment by filipkrstic** [comment]
Of course I do. W3 Validators says: "No errors or warnings to show.", then I compared commits difference in code and visually at the end.

**Pull request merged**
