### PR TITLE
fullcalendar console error fixed for #277

### PR DESCRIPTION
**Pull request by irfanevrens**

### CODE REVIEW

**Comment by irfanevrens** [comment]
fixed for issue #277

**Comment by jepperaskdk** [comment]
Cool, do you know how to reproduce the stacktrace?

**Comment by irfanevrens** [comment]
If there is no element in html, using this plugin give an error.

When document.getElementById('calendar') return undefined.

**Comment by jepperaskdk** [comment]
Ah - didn't realize this error is triggered on all pages, except calendar.html. Good job!
@puikinsh Lets merge this one.

**Pull request merged**
